### ISSUE TITLE
Build broken by new API for Retrofit.RestAdapter

### ISSUE THREAD

**Issue by ekarcnevets** [xiprox/WaniKani-for-Android#11]
This is now Retrofit.Retrofit.Builder. Docs at http://square.github.io/retrofit/. Unsure if you've got a patch for this yet.

**Comment by xiprox** [comment]
Yes, a lot has changed in retrofit with version 2.0.0. While I haven't updated the code to work on the new version, it's easy to get a build succeed. All you need to do is to change the version of the retrofit dependency line in build.gradle from `+` to `1.9.+`.

**Comment by ekarcnevets** [comment]
Yeah thanks, I've figured that out now. I'm taking a look at issue #10, it looks like the API response for critical items don't include the user specific data.

**Comment by xiprox** [comment]
Please see my reply in #10.

**Comment by xiprox** [comment]
Retrofit will be locked at `1.9.0` in this project, as long as it works.
