### ISSUE TITLE
Horrible battery drain

### ISSUE THREAD

**Issue by kufii** [xiprox/WaniKani-for-Android#14]
With this app installed and idle I'm consistently losing around 3-4 hours of screen on time

**Comment by kufii** [comment]
as far as I can tell it's linked to the notifications

**Comment by xiprox** [comment]
Hello,

Unfortunately, I'm not actively developing this app. It was my first "real" app project and I was extremely inexperienced. The code is bad and I can't find the dedication in myself to dive into this mess and fix it all. However, I do hope to rewrite the app from scratch someday, fixing the current issues along the way.

**Comment by kufii** [comment]
Hey no problem, I'm looking into it and I think I may of found the issue. I want to test for a bit and submit a pull request if the fix works. If I do that can you republish to the play store?

**Comment by xiprox** [comment]
Thanks. Yeah, I should be able to do that. However, if I recall correctly, the latest changes in ItemDetailsActivity were half done. Will need to finish those for a proper update.

**Comment by kufii** [comment]
What were the changes? If you give me the details I can look into doing that too

**Comment by xiprox** [comment]
Well, ddd2939. Let me see what it looks like right now.

**Comment by kufii** [comment]
fixed with https://github.com/xiprox/WaniKani-for-Android/pull/16

could you let me know when it's been pushed to the play store? Thanks!
