### ISSUE TITLE
[Feature request] reading>meaning

### ISSUE THREAD

**Issue by Amenophyckxs** [xiprox/WaniKani-for-Android#17]
Hey, I really like this app, but ever since starting on wanikani, I have been using a userscript that changes the order of my reviews to reading>meaning, instead of the default meaning>reading. Thus forcing me to remember the reading first and "helping" me think in Japanese (if that makes sense)

I would love to see an option added to change the order in the app also since it really throws me off every time I do my reviews on my phone, I have to actively remember to type the meaning first.

I hope this is at all possible, and if that is too much effort to implement an additional order, maybe it is easier or faster to just replace the order and have a separate apk with only the reading>meaning order?

**Comment by Amenophyckxs** [comment]
Almost 3 months went by without a single comment (asked through mail also.
I guess that I should forget about it. 
Wish there was at least SOME feedback, even a no. Just total ignoring is kind of lame

**Comment by xiprox** [comment]
Hello,

Well, honestly, as I noted elsewhere too, I'm not actively working on this app. In fact, you could even say that development is in a stalled state right now. I do have hopes to one day get back but yeah...

I did see this issue back in the day, yeah. But I put it aside for later. Then eventually forgot. Totally my bad and yeah, insult me as much as you want on that.

As for the userscript implementation, that part of the app was adapted form the old WaniKani Mobile project (with permission) and I have no idea how things worked after all this time. Hopefully though, when I eventually get around to rewriting this app, I'll get back to this. But things being the way they are, please don't expect anything.

**Comment by Amenophyckxs** [comment]
no insult intended, merely asking for a single reply so i have an idea where things stand.
thank you for the feedback.
i look forward to your future rewrite.
