### ISSUE TITLE
Dev branch issues

### ISSUE THREAD

**Issue by edluo1** [xiprox/WaniKani-for-Android#18]
I've been trying to work on a thing I think may need changing in the app, but when I run the dev branch it seems like there's a few problems with it that I don't see in the Google Play Store version:
1. No notifications are shown at all when review time comes up or even after.
2. Sometimes the vocabulary doesn't update itself after going to the next one, so sometimes for a vocab term, the displayed prompt is for the "vocabulary meaning" but you're actually supposed to input the reading. Other times, the wrong kanji shows up and doesn't update until you press a different button.
3. The checkmark box marking things recently completed doesn't update properly.
4. The app crashed in the Vocabulary section when I tapped the filtering button twice in a row sometimes.

Settings enabled:
Use custom fonts
Recent unlock number: 3
Enable notifications
Enable reminder notification
All the default userscripts + Mistake delay

Is there anything I can do to deal with these things?

**Comment by xiprox** [comment]
_sigh_

Honestly, I have no idea what's going around anymore. I'm hoping to rewrite the whole app from scratch, but I don't know if I'll find time for that anytime soon. Thought summer would be a good chance but not so sure anymore.

And hello.

**Comment by edluo1** [comment]
Hi,

Actually, I found out a fix within the app for part 2. Checking the checkbox for "enable hardware acceleration" in the settings allows the kanji and the input expected (reading, meaning, on'yomi or kun'yomi). I don't know how come it only updates when the buttons 🕘, ✔️, 👁, or ひ are clicked without the hardware acceleration, though.

Also, it doesn't help with the notifications not updating properly.
