### ISSUE TITLE
[Feature] Auto-advance on correct answer without pressing Enter

### ISSUE THREAD

**Issue by Aralox** [xiprox/WaniKani-for-Android#21]
Similar to Memrise's system where you automatically progress to the next question if you have typed the correct answer.

Rough idea on how to implement this:

1. At the start of the review session, obtain a list of all items to be reviewed, perhaps by combining the 'active' and 'review' queues like in the [`ReviewOrder` script](https://github.com/xiprox/WaniKani-for-Android/blob/a69ccc7bac8550f6785861cf7f1eddf0dbf575b5/WaniKani/src/tr/xip/wanikani/userscripts/ReviewOrder.java#L122).
2. Obtain a list of correct answers for every item in that review list, be it a collection of meanings or kana readings. Do this by making a list of all the levels spanned by the items in the review list, then loading information for those levels using the [WaniKani API](https://github.com/xiprox/WaniKani-for-Android/blob/a69ccc7bac8550f6785861cf7f1eddf0dbf575b5/WaniKani/src/tr/xip/wanikani/client/WaniKaniApi.java#L73-L83). All the items and the information we need will now be in one `List<BaseItem>`. It might be a good idea to discard unneeded items, then turn the list into a dictionary keyed by item character. Producing this dictionary only needs to be done once per review session.
3. During the review, after a letter is typed (romanji or kana), check if the full answer exactly matches any of the allowed answers. If so, [progress to the next question](https://github.com/xiprox/WaniKani-for-Android/blob/a69ccc7bac8550f6785861cf7f1eddf0dbf575b5/WaniKani/src/tr/xip/wanikani/userscripts/WaniKaniImprove.java#L268).

**Comment by xiprox** [comment]
As I noted here and elsewhere before, I haven't been actively working on this app. I'll get around to merging #20, but I won't be able to work on features or review them much. Hopes are that a rewrite will be done someday. When that happens, ideas like these can be put on the table.
