### ISSUE TITLE
Way to tell lvl up?

### ISSUE THREAD

**Issue by Emrayla** [xiprox/WaniKani-for-Android#24]
It would be great if you could tell when a radical/kanji/vocab actually goes up or down a level (apprentice to guru for example) when you are reviewing.

**Comment by xiprox** [comment]
Hello, could be looked into eventually, but as I previously noted here and elsewhere, I'm not actively working on this project. Please don't expect anything.

**Comment by xiprox** [comment]
Won't be able to do get around to this, unfortunately.
