### ISSUE TITLE
Can't edit meaning notes during reviews

### ISSUE THREAD

**Issue by Emrayla** [xiprox/WaniKani-for-Android#27]
I type a letter or two and then the box deselects. Happens every time I select the text box.

**Comment by xiprox** [comment]
Yeah, this is a known issue. Might or might not be fixed sometime soon.

**Comment by elbie** [comment]
I'm also having this issue.

By known issue, are you referring to issue #9?  You mention the globe icon there.  Do you mean the eyeball?

After answering a review (whether correctly or not), I click on the meaning icon (the eyeball), then click on the "Click to add note" box in the Reading/Meaning Note area.
