### ISSUE TITLE
Problems with some userscripts

### ISSUE THREAD

**Issue by Darky1** [xiprox/WaniKani-for-Android#3]
I'm having problems with "Review order" and "Lesson order".
Both aren't showing in reviews or lessons.

"Review improvements" is enabled and things like the "Ignore button" or the "WaniKani improve" are working as intended.

Already tryed to activate/deactivate it
App version: 1.1.1
Phone: https://www.dropbox.com/s/21cxryfy5tut75d/Screenshot_2015-05-01-20-32-59.png?dl=0

If you need more information, please let me know!

Best regards
Darky

**Comment by xiprox** [comment]
Hello,

Yes, I'm aware of this issue. I won't be able to promise a certain date for a fix but I'll look into it in the near future.

**Comment by xiprox** [comment]
Review order and Lesson order userscripts won't be supported. I don't see the effort worth it, since it'll be trashed once we use a native way for handling reviews.
