### ISSUE TITLE
Cannot enter katakana by using uppercase

### ISSUE THREAD

**Issue by elbie** [xiprox/WaniKani-for-Android#32]
When trying to enter katakana by using the uppercase english alphabet, the uppercase letters are converted to lowercase automatically, and thus only hiragana can be entered.

This is not critical, since all the readings that have katakana have readings with the equivalent hiragana as well, but it would be nice to be able to type katakana properly.

**Comment by xiprox** [comment]
Hello,

Yes, you are right. And I agree that it would be nice.

However, as you see, I haven't been doing much work on this app for quite a long while now. Currently, I'm planning to push all the new changes up and at least keep the app updated a little more with fixes and such. That being said, I really don't think I will have enough time to work on "features".

Closing this...
