### ISSUE TITLE
App requires login to do reviews but username/password is always incorrect

### ISSUE THREAD

**Issue by wunderbunny** [xiprox/WaniKani-for-Android#34]
At about 29 November 2016, the WaniKani developers made some changes and described them as follows:

_**Nothing was done to the API. Any changes to the API are versioned, and thus shouldn't break the scripts...

Some minor changes to the javascript for both lessons and reviews were made.  The site's jQuery dependency was just updated to latest (we were four versions behind); there were a few deprecations we had to address and it (our changes or the scripts dependency on our loaded jQuery) may have caused the scripts to break.

You'll need to contact the script authors since we don't officially support the scripts.**_

Since that time, I have been unable to do reviews or lessons with the app.  I can see how many reviews / lessons I have because the API is being processed correctly.  When I try to do a review, I am prompted to enter email/username + password.  Then I press "sign in".  I always get a message about "incorrect username / password".  I have done this at least ten times.  Other people have reported the same difficulty on the WaniKani forum thread for this app.

Perhaps your code needs to be reviewed and/or recompiled to resolve this issue?

I installed this app on Sony Xperia Z2 android 6.0.1.

Many thanks for making this app available.

**Comment by xiprox** [comment]
Answered at https://www.wanikani.com/chat/api-and-third-party-apps/6233/page/15#post394793
