### ISSUE TITLE
Single mode is default now...?

### ISSUE THREAD

**Issue by obskyr** [xiprox/WaniKani-for-Android#37]
I'm sure it was intentional, but single mode seems to be on by default right now. Is that really a good idea?

Seeing as it's not a part of the default desktop WaniKani experience, it's odd that it would be in this app. What's more, the little `1` symbol doesn't really make it at all clear what it does, introducing a confusing new workflow for people who haven't used it before, with the way to turn it off not being apparent.

**Comment by xiprox** [comment]
Yes, I completely share your opinions. I was thinking about it yesterday and will be changing it back.

**Comment by nico** [comment]
+1

Also, if I disable "show single mode button" in settings, things are always in single mode, and the button doesn't remember my choice. So I can't disable that setting and I always have to disable the setting every time I practice.

Also also, the button never shows up for lessons, only for reviews, so lessons now always have to be done in single mode.

(But thank you so much for this app, it's really really well done!)

**Comment by obskyr** [comment]
Ah, I noticed that the single mode choice thing persists even when you turn
off the button, but I thought maybe it was intentional to allow "permanent"
single mode without the button present. The fact that it doesn't remember
your choice is an issue for sure, though!

2017/01/04 20:41 "Nico Weber" <notifications@github.com>:

**Comment by squasheds** [comment]
+1 as well, caught by surprise, I thought something had gone wrong.

**Comment by xiprox** [comment]
@nico Single mode only puts your reading and meaning reviews for the same item one after the other. I don't think it has any effect to your lessons. Hence, why it's not there.
