### ISSUE TITLE
New level lessons mixed with old level

### ISSUE THREAD

**Issue by anschch** [xiprox/WaniKani-for-Android#39]
I just reached level 2 although I hadn't even unlocked every vocab on level 1 yet. So now I have ~50 new level 2 lessons mixed with lessons from level 1, and the lesson order seems to be totally random.

I would like to finish level 1 before starting on level 2. Is it possible to delay or selectively do the level 1 lessons first?

**Comment by xiprox** [comment]
Hello,

This is something related to [wanikani.com](wanikani.com), the site itself, and not really anything to do with this _unofficial_ client app. I suggest you take your question to the [wanikani forums](wanikani.com/chat) or shoot an email to hello@wanikani.com.

**Comment by anschch** [comment]
Ok I see! My apologies.

**Comment by xiprox** [comment]
It's all fine! Good luck in your studies! 👍
