### ISSUE TITLE
Mute button mutes whole device 

### ISSUE THREAD

**Issue by chibi03** [xiprox/WaniKani-for-Android#40]
For some reason the mute button mutes my whole device when enabled. I'm not sure if jt was caused by the last update of the app or my OS update. 
Device info: OnePlus 3,  Oxygen OS 4.0.2, Android 7.0
Have there been any other cases of this happening? 
Thanks

**Comment by imasaru** [comment]
I can reproduce this also, just as a confirmation. 
Device Info: Amazon Kindle Fire HDX (1st gen.), running LineageOS 14.1 (Android 7.1.1) 
Thank you for this app!

**Comment by xiprox** [comment]
This is not a _bug_. The behavior could be improved, but for the time being there are no plans.
