### ISSUE TITLE
Switching to other task kills app

### ISSUE THREAD

**Issue by squasheds** [xiprox/WaniKani-for-Android#43]
This just started happening now and havent made any changes to my phones configuration.

Whenever I change to another task or go to the desktop, the app doesnt remain open in background. When pressing the square every other recent app apears save for WK. Even if pressing square while on WK, it doesnt appear as a recent/open app, as if it were running incognito or something.

Obviously, when I open WK again, my study o review session must be restarted and I have lost some progress.

Has this happened to anyone?

**Comment by xiprox** [comment]
Hello,

I really don't think this is something related to the app itself. What system are you using?

**Comment by squasheds** [comment]
Android 6.0 on a Huawei p9 lite (VNS-L23) with EMUI 4.1

**Comment by xiprox** [comment]
I'd think that, if it were a case of the app being killed off. In that case the app would still show up as a recents item though. Disappearing seems strange.

**Comment by xiprox** [comment]
@squasheds Are you around? Do you still have the same problem?

**Comment by squasheds** [comment]
Nope, problem has been solved for a long time now, I believe after I reinstalled the app. I’m still not getting audio autoplay though =P

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by imasaru** [comment]
Oh yes, I can confirm as well that the autoplay doesn't work. I forgot about that... It isn't script-related, though, is it?

**Comment by xiprox** [comment]
Oh, I guess that's nice to hear. I'll be closing this. 😄 

Did you guys try out the alpha? The fix is for audio autoplay in reviews is up only there for the time being. ([see for info on alpha](https://github.com/xiprox/WaniKani-for-Android#alpha-testing))

**Comment by imasaru** [comment]
Ooh, don't mind if I do... :)
