### ISSUE TITLE
Opening the 'Item Info' panel during review disables WKImprove script (auto-forward)

### ISSUE THREAD

**Issue by Aralox** [xiprox/WaniKani-for-Android#46]
To reproduce this,

- Enable 'Wanikani Improve' script in settings
- Start review, get something wrong
- Click on the 'item info' panel (eye icon)
- Continue with reviews. Thereafter, the auto-forward feature of the 'Wanikani improve' script is disabled.

Android 7.0, latest dev branch (and also release branch).

The 'item info' panel is a part of the official Wanikani review page, so the problem seems to lie with the WKImprove javascript somewhere.

Logcat:
```
07-02 22:46:09.075 22008-22008/tr.xip.wanikani:webview I/chromium: [INFO:CONSOLE(1)] "answerException: wrong answer", source:  (1)
07-02 22:46:09.075 22008-22008/tr.xip.wanikani:webview I/chromium: [INFO:CONSOLE(1)] "Wrong answer", source:  (1)
<I click on the item info panel>
07-02 22:46:24.960 22008-22008/tr.xip.wanikani:webview W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
07-02 22:46:24.989 22008-22008/tr.xip.wanikani:webview D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: true
07-02 22:46:24.989 22008-22008/tr.xip.wanikani:webview D/cr_Ime: [InputMethodManagerWrapper.java:68] hideSoftInputFromWindow
<From here, console messages from WKImprove script do not show up anymore>
```
I've identified that `answerException` (`answerException = $.trim($('#answer-exception').text());`) in `WaniKaniImprove.java` is blank after the item info panel is opened.

I compared the body html of a wrong answer when the item info panel had not been opened with the html of a wrong answer after it had been opened, and found that the `answer-exception` element was missing in the latter case.

I'm working on this issue, but any advice would be appreciated. :)

**Comment by Aralox** [comment]
I've solved this issue by introducing a 300 ms delay between clicking the 'next' button and calling the 'checkAnswer()' function. I changed the call to `checkAnswer()` in `WaniKaniImprove.java` to `setTimeout(checkAnswer, 300)`.

I identified that the official review site does correctly update the html elements, and solved the problem by assuming that for some reason, after the info-panel is clicked, all subsequent html is updated slightly too slow for the `checkAnswer()` function to pick up.

I'll mark this issue as resolved once I put through a pull request. I want to see if I can solve a few other issues first.

**Comment by xiprox** [comment]
Hey,

Are you still planning to open a PR for this?

**Comment by Aralox** [comment]
Hey Ihsan, yeah I am, was just putting this off because of work. I'll get on this now! :)

**Comment by xiprox** [comment]
Aright! Thanks for the help. PR merged
