### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [xiprox/WaniKani-for-Android#47]
Hi @xiprox 

Since the app is licensed under GNU GPL v3, can you consider adding this app to the F-Droid repository? (I don't know if you're using proprietary libraries, but it doesn't works with F-Droid, we sometimes can build the app without them)

I can give you documentation and links if you need it ;)

**Comment by xiprox** [comment]
Hello. Unfortunately, I am not planning to upload the app to F-Droid.

**Comment by Poussinou** [comment]
No problem
