### ISSUE TITLE
Crash on app start up as soon as API code is input

### ISSUE THREAD

**Issue by Be-ran** [xiprox/WaniKani-for-Android#48]
"WaniKani has stopped" crash on app start up as soon as API code is input - Any fixes or am I being dumb? (Android Galaxy s6)

**Comment by xiprox** [comment]
Hello,

Was it happening once? Was the app working properly after a relaunch? If so, I think I just published a fix to the alpha channel. If you're around, can you try it out? ([see for info on alpha testing](https://github.com/xiprox/WaniKani-for-Android#alpha-testing))

**Comment by Be-ran** [comment]
Hello,

Yes this fix works thanks!
