### ISSUE TITLE
Simplify Login Experience

### ISSUE THREAD

**Issue by imasaru** [xiprox/WaniKani-for-Android#50]
Hey İhsan,

I just had an idea for simplifying the initial login process... I thought that the user could log in to WaniKani using the _in-app browser_ instead of another installed one. That way, the user could log in to WK, fetch the API key, and then be able to start immediately using the app without having to go to Lessons or Reviews and need to log in again before gettinng started, because the in-app browser would preserve the login status(right?)

I did something similar for the WaniKani Companion extension for Chrome, and it worked out well. I just inserted a direct link to the API Key header on the WK settings page. It is this:

**Comment by xiprox** [comment]
I have a a similar solution where instead of the user inputting credentials into a browser and the app fetching things from there, the user inputs credentials natively and the app takes care of everything else in the background. However, that's for a different project. :)

Also, _this_?

**Comment by imasaru** [comment]
For the "this", I was going to find a link to show what I used, but since you want to do the login natively, I guess I don't need that anymore :smile:

**Comment by xiprox** [comment]
I see. In that case, shall we close this issue?
