### ISSUE TITLE
App gets stuck after correct answer in Reviews

### ISSUE THREAD

**Issue by squasheds** [xiprox/WaniKani-for-Android#51]
Running the latest Alpha version.

Sometimes, after correctly answering a Reading question and clicking to go on, its answer seems to be dragged into the next question, which becomes un-answerable and un-skipable. Once this happens, it is imposible to go forward (sacrificing the current question) because the > arrow won't do anything, only going back by pressing Home or <- arrow is posible. It has happened about five times since installing the Alpha a couple of days back.

In this case, previous question was "ganmen" and, I believe, this reading was "tombstone" (or whatever it might have been XD). As can be seen, to to and ne were added to the previous "ganmen" as I tried to answer this new question.

![screenshot_2017-09-05-23-28-04](https://user-images.githubusercontent.com/24930847/30094663-35aa313a-9293-11e7-88c6-bfab5c000428.png)

**Comment by xiprox** [comment]
I'm aware. It's been happening to me as well and it's annoying as hell. Pretty sure it was introduced with #49. Haven't had the time to look into it yet though.

**Comment by xiprox** [comment]
@Aralox If you have an idea or could tackle this anytime soon, that'd be great.

**Comment by Aralox** [comment]
I'll have a look tomorrow after work (2245 at the moment)

**Comment by Aralox** [comment]
Submitted a PR (#52). It's a pretty simple bug which I should have found before submitting my last pull request - my bad. 

I had to create a new WaniKani account to test reviewing radicals, as I have too many vocab reviews on my main account. I've not tested the exact scenario you described @squasheds, as I don't have any reading reviews available yet. I'm fairly confident it only happens for radicals, but please try out the fix and let me know anyway. I'll verify it once I unlock some kanji on my new account :).

**Comment by xiprox** [comment]
I'll be taking a look at the #52 shortly.

And yes, on-topic names for branches would probably be nice.

**Comment by squasheds** [comment]
Has the fix been implemented in the available beta at playstore? I downloaded it three days ago and there has been no new update. I just had the bug happen twice again today when going from a reading question to a radical one. Yesterday it also happened when going from a meaning question though I dont remember to which kind of question it crossed.

**Comment by xiprox** [comment]
@squasheds The change is now up on the **alpha** track on the Play Store. I haven't been able to test it myself, so can't say if it works for sure.

**Comment by madmalkav** [comment]
App updated 3 hours ago, problem persist on my phone. Any debug log or other info I can contribute?

**Comment by xiprox** [comment]
I just did around 40 reviews in different batches and had no occurrences of this issue. In contrast, reverting #52 brings back the error even with only a few reviews.

@madmalkav Are you sure you are on the latest **alpha**, again? Though, I'll promote alpha to beta so you should get it there in a bit anyway.

**Comment by madmalkav** [comment]
Ouch, you are completely right, I'm on Beta channel.

**Comment by xiprox** [comment]
Ok. I take it that it's solved for you as well now? Guess this issue can be closed.

**Comment by madmalkav** [comment]
Haven't the chance to test yet, as soon as I can I'll reupdate the app and
retry.
