### ISSUE TITLE
Lessons quiz input gets stuck at ignored state after first batch

### ISSUE THREAD

**Issue by xiprox** [xiprox/WaniKani-for-Android#54]
Finishing a batch of lessons and getting to the quiz of the next batch, a user is greeted with an orange input field (ignored state) and there's no way to turn it into normal or to submit an answer right there. Thankfully, they can switch to another app (or open the recent apps menu, really), come back to WaniKani, and the problem will be solved.

Can be reproduced in latest alpha. Other releases not tested.

**Comment by nickjohnson-dev** [comment]
I'm seeing this behavior this morning in v1.2.4.

Thanks for including a workaround in the description. I'll just use that for now.

P.S. Thanks for your work on this app. It's been a huge help having convenient access to the WaniKani webapp.

**Comment by xiprox** [comment]
Hello. Glad you like the app.

I originally wanted to fix this before publishing an update but haven't really been able to do any work lately. Considering some major issues would be fixed by publishing an update, I decided the compromise was worth it.

Back to the issue, I feel like this was introduced somehow with the recent changes by @Aralox. It would be awfully helpful if you could check this out real quick, @Aralox.

**Comment by nickjohnson-dev** [comment]
I totally understand the logic behind releasing the update and I think you made the right call.

I only do lessons once a week, so it's not a huge issue for me.

Just wanted to make sure you were aware that it made it into the released build.

Thanks again.

**Comment by Aralox** [comment]
Hi guys, my PR should sort this out. Please try it out and let me know if you run into any more problems. Thanks for alerting me to this Ihsan.

**Comment by xiprox** [comment]
@Aralox In fact, I thank you for the quick fix! One minor issue left with the input field is that the previous answer text seems to not get cleared.

@nickjohnson-dev Just published an update with the fix in. You should be receiving it soon.

**Comment by Aralox** [comment]
No worries mate. I've sorted out the uncleared previous answer issue with PR #61
