### ISSUE TITLE
Unable to edit synonyms

### ISSUE THREAD

**Issue by voidzero** [xiprox/WaniKani-for-Android#56]
When editing / adding a synonym, the keyboard only shows for something like 5 seconds before disappearing again.

**Comment by xiprox** [comment]
Hello. This was fixed a while ago. Apparently the [existing issue](https://github.com/xiprox/WaniKani-for-Android/issues/27) got closed by github on commit push. The fix hadn't yet made it to the production release though. I'll be promoting it from beta to production shortly.

**Comment by xiprox** [comment]
The fix should be live as an update.

**Comment by voidzero** [comment]
Thank you :bowing_man:
