### ISSUE TITLE
Display on'yomi in katakana

### ISSUE THREAD

**Issue by voidzero** [xiprox/WaniKani-for-Android#57]
I'd like to request this feature because I'm used to learning them in katakana - my wife also would like this because it really helps her to train her katakana.

**Comment by xiprox** [comment]
Hello. This data is obtained directly from wanikani.com. The unofficial android app here shows the data as-is. You would have to take this up to Tofugu Inc.

**Comment by voidzero** [comment]
Alright. Just wondering - there is a userscript that can do this; is that an option?

**Comment by xiprox** [comment]
It may be, but I don't think I'll be adding another userscript at the moment.
