### ISSUE TITLE
Full screen text input in landscape with hardware keyboard

### ISSUE THREAD

**Issue by nibarius** [xiprox/WaniKani-for-Android#6]
How to reproduce:
1. Connect a bluetooth keyboard to your phone.
2. Rotate phone to landscape
3. Do reviews in the app.

Expected result:
I should be able to do reviews while still seeing the input field. Since I'm using a hardware keyboard there is no virtual keyboard that takes up half the screen and there is no need to show a full screen text input widget.

Actual result:
A full screen text input widget is shown, so I can't see the rest of the web page. Makes hardware keyboard + landscape mode on a phone more or less useless.

**Comment by xiprox** [comment]
The current reviews screen will be changed completely. I don't think I'll put more work into the current implementation.

On a different note, I don't know how much of this issue concerns the app. It sounds more like something to do with the OS.
