### ISSUE TITLE
Pixel 2 Android 8.1 Won't Load

### ISSUE THREAD

**Issue by ctruzzi** [xiprox/WaniKani-for-Android#62]
It appears that issues are supposed to be posted here instead of the wanikani community forum. After the app accept my API Key the dashboard does nothing but load, same if I attempt to press most pages. However if i click "review" or "lessons" it will go to my current lessons and reviews in the app. I am not getting any errors posted or any other messages so I am unsure if there is a way I can post a log.

**Comment by xiprox** [comment]
Hello. Have you resolved this?

**Comment by ctruzzi** [comment]
Not certain what changed, the API calls on the website where working fine but it failed to load until I installed a local logging application. Loses as of a few hours ago properly.

**Comment by alexbutterworth** [comment]
I have the same issue on a Pixel 2 also: the WK app accepts the API key but is unable to retrieve any homepage information (loading icon just spins indefinitely). Lessons and reviews can be started but I don't think progress is being tracked.

**Comment by ctruzzi** [comment]
@alexbutterworth Not certain if it will really help but I've done it on 2 Pixel 2 XL's now. I installed `aLogcat (free)` and somehow right after closing WK, starting the logger and restarting WK it worked properly and continues to work. It doesn't seem like it should help at all but has twice for me.

**Comment by alexbutterworth** [comment]
@ctruzzi I followed your suggestion and it worked like a charm, thanks! I agree that it seems like an unlikely workaround; I can only imagine that `aLogcat (free)` initialises some required background service which WK requires to perform the initial progress sync. Anyway, thanks again for your help!
