### ISSUE TITLE
WK app crashing after API input

### ISSUE THREAD

**Issue by Oozorin** [xiprox/WaniKani-for-Android#63]
Hi!

I've had the same issue as Be-ran (https://github.com/xiprox/WaniKani-for-Android/issues/48) - the answer there was to apply for Alpha-testing, but I can't seem to be able to do that: google says I'm not eligible to apply for alpha testing. Is there something I can do?

**Comment by matchai** [comment]
I've been encountering the same issue, so I've gone ahead and sent you a bug report to your email.
Please let me know if you need anything else from my end!  😁

**Comment by xiprox** [comment]
@matchai thanks for the report. I'm investigating it.

**Comment by xiprox** [comment]
Hello all. This should be fixed with d366739ec4c71a5e5b5fde9d3bf4cf34e4348c0b. Please reopen this issue if you continue experiencing crashes even after updating to v1.2.7 (should be on the Play Store within an hour).
