### ISSUE TITLE
Dashboard will not refresh

### ISSUE THREAD

**Issue by seandub89** [xiprox/WaniKani-for-Android#66]
My dashboard on the app won't refresh and has been stuck with the same data for months. The app still works when you click on "Reviews". It does take you to your current reviews, it's just the dashboard as well as the Android notification prompt do not refresh. 

Also appears to be constantly refreshing, but never actually doing so.

![screenshot_20171125-132221](https://user-images.githubusercontent.com/33990055/33234950-e55351ea-d1e3-11e7-9c16-e0f14331df5e.png)

New to Git Hub, apologize if this isn't the right way to file a bug.

**Comment by xiprox** [comment]
Hello!

Have you possibly renewed your API key? Did you try to log out and back in?

**Comment by seandub89** [comment]
I've tried both and still have the same issue. Wanikani does have a new API
thats in beta, should I use that?

**Comment by xiprox** [comment]
Glad to hear that! I'll be closing this issue then.
