### ISSUE TITLE
Add contact method

### ISSUE THREAD

**Issue by voidzero** [xiprox/WaniKani-for-Android#67]
Hi, I just wanted to send you a small message thanking you for the work you've done on the app, to accompany the in-app donation I also sent you 😄

But I couldn't find contact info, and since the app also has no contact button, I'll just write it here.

Hope you'll get yourself something nice to eat!

またね~~

**Comment by xiprox** [comment]
Hi! Thanks for the nice words and the donation. :slightly_smiling_face: 

And hmm, maybe I should add a contact link inside the app as well. :thinking:
