### ISSUE TITLE
WaniKani keyboard shortcuts doesn't work during reviews with hardware keyboard

### ISSUE THREAD

**Issue by nibarius** [xiprox/WaniKani-for-Android#7]
How to reproduce:
1. Connect a bluetooth keyboard to your phone.
2. Do reviews in WaniKani.

Expected results:
Pressing enter should submit the answer, Pressing "f" should show details after an answer has been submitted. Pressing space should show more details.

Actual results:
Enter doesn't submit the entered text. Pressing other keys doesn't invoke the expected keyboard shortucts WaniKani supports.

It's like keypresses from the external keyboard isn't forwarded to the WebView.

**Comment by xiprox** [comment]
The current reviews screen will be changed completely. I don't think I'll put more work into the current implementation.
