### ISSUE TITLE
Offline Compatibility

### ISSUE THREAD

**Issue by caionovaes** [xiprox/WaniKani-for-Android#70]
Just lost my remote connection for like a week... Only time I have to study is during commute.
So I wondered... Could WaniKani work offline and once you have connection available, sync?

**Comment by xiprox** [comment]
Hello,

Actually, all the native parts of the app work offline - whatever you load, will be there next time you check offline. Reviews and Lessons (which are just a wrapped browser), however, depend on real-time connection to WaniKani servers and with the current APIs there's no way we can implement offline-first reviews.

**Comment by caionovaes** [comment]
I was afraid of that... Oh well. And thanks for the app!
