### ISSUE TITLE
last version

### ISSUE THREAD

**Issue by IzzySoft** [xiprox/WaniKani-for-Android#73]
Could you please [tag](https://github.com/xiprox/WaniKani-for-Android/releases) the last version and attach the APK, @xiprox? The `releases/` page still shows v1.2.3 as latest version, but according to `build.gradle` there's already v1.2.7.

Thanks in advance!

**Comment by xiprox** [comment]
Hello,

I have stopped tagging releases and uploading APKs since 1.2.3. Currently the only supported distribution method is the Google Play Store.

**Comment by IzzySoft** [comment]
That's very sad news for those who don't use Playstore (because either they can't, or they consciously decided against e.g. for privacy reasons). Could you reconsider that decision please?
