### ISSUE TITLE
Keyboard keeps closing on note-taking

### ISSUE THREAD

**Issue by seangenabe** [xiprox/WaniKani-for-Android#9]
When typing into reading / meaning notes, the keyboard appears, but suddenly closes.

**Comment by xiprox** [comment]
Hello. Are you sure it's not an issue on your side? It seems to be working fine. On what device are you running?

**Comment by seangenabe** [comment]
I have an Acer Z220 (pretty unpopular) running Android 5.0.1. I do have a few scripts enabled. I'm just using the default Google English keyboard.

**Comment by xiprox** [comment]
We are talking about the built-in browser that you can access with the globe icon, right? I had included that internal browser only to make it possible to easily access more information (that the WaniKani API doesn't provide). I'm thinking of replacing it sometime, anyways. I can't reproduce the error. It's probably something to do with your device. I don't think I'll be able to help you here.
